CREATE DATABASE quiz_multiplayer;
USE quiz_multiplayer;

CREATE TABLE QUESTION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    QUESTION_TEXT VARCHAR(255) NOT NULL,
    CORRECT_OPTION VARCHAR(100) NOT NULL,
    OTHER_OPTION_1 VARCHAR(100) NOT NULL,
    OTHER_OPTION_2 VARCHAR(100) NOT NULL,
    OTHER_OPTION_3 VARCHAR(100) NOT NULL
);

CREATE TABLE PLAYER (
    NICKNAME VARCHAR(20) PRIMARY KEY,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    IS_ADMIN BOOLEAN NOT NULL,
    TOTAL_SCORE INT DEFAULT 0
);

CREATE TABLE GAME_MATCH (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NICKNAME VARCHAR(20) NOT NULL,
    SCORE INT NOT NULL,
    DATE_PLAYED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (NICKNAME) REFERENCES PLAYER(NICKNAME)
);